name: MafiaPlugin
version: '${project.version}'
main: as.mafiaplugin.MafiaPlugin
api-version: 1.19
commands:
  ready:
    description: 잘될까 과연?
    usage: /ready
    aliases: [레디]
  han:
    description: 테스트 명령어
    usage: /han
    executor: as.MafiaPlugin.Han
  start:
    description: 제발되라
    usage: /start
    aliases: [스타트]
  search:
    description: search
    usage: /search <playername>
    executor: [서치]
  protect:
    description: protect
    usage: /protecy <playername>
    executor: [프로텍트]